### ISSUE TITLE
Dependency to TreeTagger / other POS taggers

### ISSUE THREAD

**Issue by jimkont** [HeidelTime/heideltime#38]
Hi

We would like to include HeidelTime to the [DBpedia](http://dbpedia.org) information extraction framework (see https://github.com/dbpedia/extraction-framework/pull/447 & https://github.com/dbpedia/extraction-framework/issues/446).

A contributor tried to work on this integration but also added a lot of TreeTagger files int the repo
as requested in your documentation pdf. We would like to avoid that is possible so, we 'd like to ask:

* Can we use another POS tagger instead? (with a dependency mostly from maven)?
* if yes, DBpedia parses text from Wikipedia only but in many languages, which tagger would you recommend in this case?

Thanks in advance for your help & guidance

**Comment by Hronom** [comment]
Here is  my 50 cent, POS taggers from https://languagetool.org/ 
```
org.languagetool.tagging.en.EnglishTagger
org.languagetool.tagging.ru.RussianTagger
org.languagetool.tagging.de.GermanTagger
...
```
Maven:
```xml
        <dependency>
            <groupId>org.languagetool</groupId>
            <artifactId>language-all</artifactId>
            <version>3.2</version>
        </dependency>
```

**Comment by aditya-nambiar** [comment]
In your enum POSTagger you give 4 options  
STANFORDPOSTAGGER, TREETAGGER, HUNPOS, NO
So how do I include the above POS tagger ? 
Thanks!

**Comment by jzell** [comment]
Depends on what you expect from the HeidelTime integration.

In the past, the TreeTagger with its many supported languages has offered the best results on documents where we ran comparative tests. Its support for many languages means that there's a lot of parameter files, additionally it isn't portable since it runs native code. It has no support for e.g. Arabic, Hungarian, Croatian. Russian and Chinese are kinda messy to set up.

An alternative would be to use the [Stanford POS Tagger](http://nlp.stanford.edu/software/tagger.shtml). The clutter is greatly reduced, it's a portable Java-only solution and there's a [Maven candidate](http://mvnrepository.com/artifact/edu.stanford.nlp/stanford-corenlp). However, its list of supported languages is considerably shorter, and there seem to be some quirks parallelizing it.

For these two preprocessors, we have annotators that generate UIMA annotations in the pipeline given a raw input text (from a UIMA Collection Reader). For any other preprocessing solutions, someone would have to go ahead and write an annotator that creates these annotations as expected by HeidelTime, i.e. of types `de.unihd.dbs.uima.types.heideltime.Sentence` and `Token`.

It is probably worth mentioning that HeidelTime's resources and thus the quality of the results are weakly dependent on the part of speech (POS) tags created by the preprocessing engine. We tend to stick with the tagset defined by the preprocessor/models and that's not always standardized.

@aditya-nambiar I've never worked with languagetool, but here are some steps you'd eventually have to fulfill in adding a new preprocessor:

- Create a UIMA annotator

This is where languagetools will be called with the raw text obtained from the JCAS object and its output will be translated back to a UIMA-compatible format with individual annotations. You can take e.g. `de.unihd.dbs.uima.annotator.stanfordtagger.StanfordPOSTaggerWrapper` as a template, since that also works with a Java-based import. [Lines 79/81](https://github.com/HeidelTime/heideltime/blob/master/src/de/unihd/dbs/uima/annotator/stanfordtagger/StanfordPOSTaggerWrapper.java#L79) is where you would instantiate languagetools, the [process()](https://github.com/HeidelTime/heideltime/blob/master/src/de/unihd/dbs/uima/annotator/stanfordtagger/StanfordPOSTaggerWrapper.java#L93) method is where you would have to perform a translation between the languagetools output format for tokens and sentences together with meta information (POS) to the types expected by HeidelTime.

- Create a wrapper for Standalone

In the package `de.unihd.dbs.heideltime.standalone.components.impl`, create a wrapper (again, you can base it off `StanfordPOSTaggerWrapper`) that receives the configuration from the CLI/API and wraps it to the UIMA-Annotator's expected format.

- Extend the POSTagger enum with a new member

See `de.unihd.dbs.heideltime.standalone.POSTagger`.

- Extend [`establishPartOfSpeechInformation()`](https://github.com/HeidelTime/heideltime/blob/master/src/de/unihd/dbs/heideltime/standalone/HeidelTimeStandalone.java#L340)

Ideally you'd just wanna drop another block that catches the languagetool enum element in the default block.

- (open a pull request :wink:)

From that point on, you should be able to use some `HeidelTimeStandalone.initialize()` variant with languagetools.

**NB**: I haven't worked on HeidelTime in some time, Jannik may have better input.

**Comment by jimkont** [comment]
Thank you @jzell for all the details.
I think we will give it a shot with stanford nlp for now and see how it performs.

We will reopen this if we need more help

**Comment by JannikStroetgen** [comment]
Hi @jimkont and thanks for your interest in HeidelTime. 

We are currently working on providing a GATE wrapper for HeidelTime, in the context of GATE-Time, see: http://www.derczynski.com/sheffield/papers/gate-time.pdf

The wrapper is written in such a way, that it can be used either
- to call the TreeTagger for preprocessing
or 
- to use sentence, token, pos information which is provided, i.e., created by other GATE components such as GATE ANNIE.

I guess that you perform sentence splitting, tokenization, and part-of-speech tagging in your pipeline anyway, so that HeidelTime could use this information and you do not have to call any additional tool for preprocessing at all.

If you want to, I can already provide the preliminary code of the wrapper. The code of the final wrapper will be publicly available at some later point anyway.

By the way: I guess that you mainly process non-news-style documents, right? Then, make sure to use HeidelTime to process narratives.

Cheers,
Jannik

**Comment by jimkont** [comment]
> I guess that you perform sentence splitting, tokenization, and part-of-speech tagging in your pipeline anyway, so that HeidelTime could use this information and you do not have to call any additional tool for preprocessing at all.

Actually no, we focus on semi-structured data mostly and we didn't have to use any nlp tools (so far). Date parsing is an area we could possibly improve and that is why we look into heideltime

> By the way: I guess that you mainly process non-news-style documents, right? Then, make sure to use HeidelTime to process narratives.

Our project is about extracting data from wikipedia only, e.g. http://dbpedia.org/page/Heidelberg_University
so according to the documentation, `narratives` is what we plan to use

Thanks for helping out!

Cheers,
Dimitris
