### ISSUE TITLE
GATE

### ISSUE THREAD

**Issue by mnavasloro** [HeidelTime/heideltime#58]
Hi,

I'm trying to use HeidelTime in GATE, but I get this error:
"HeidelTimeWrapper could not be initialized. Something wrong with the setup?"

I've tried changing the three parameters (file, language, type of document) but I keep getting the same message... should I do any previous step for initializing HeidelTime? Where are the instructions if this was the case? I find nothing in GATEs documentation and I have no problem with other plugins.

Thank you very much and best regards,

María

**Comment by JannikStroetgen** [comment]
Dear Maria,

The GATE-Time plugin is more or less hosted and managed by the GATE people. Some time ago I wrote a readme on how to use HeidelTime within GATE. I hope that this readme is helpful for you, but I am pretty sure that this is not the final readme for the final GATE-Time plugin.

Anyway, I attached this readme - and let's ask some "GATE people", e.g., @greenwoodma and @leondz, so that they can point you to the required information in case the readme does not help.

Please keep me posted. 

Thanks,
Jannik

[readme-heideltime-gate-wrapper-2016-03-21.pdf](https://github.com/HeidelTime/heideltime/files/1243096/readme-heideltime-gate-wrapper-2016-03-21.pdf)

**Comment by greenwoodma** [comment]
@mnavasloro Could you possibly provide the full stacktrace that is displayed when it fails as that might help me pin down where the problem is happening

**Comment by greenwoodma** [comment]
@mnavasloro from a brief bit of testing it looks as if the problem arises because the path to the config.props file has a space in it (I can reproduce the error on my machine even under Ubuntu if I put the plugin folder into a directory structure where one folder name contains a space). As yet I'm not quite sure why or how that happens, but I know there are a few places where both GATE and HeidelTime convert from URLs to File objects and back again so in one of those places there is probably something fishy going on.
I'll look into fixing this, but in the mean time just move either GATE or the plugin into a folder path without spaces in it and everything should work...... fingers crossed.

**Comment by mnavasloro** [comment]
Perfect, that was the problem indeed!

I had tried just moving the config.props file (I'd already faced the space-in-the-path problem), but it didn't work, either moving the plugin folder: I had to reinstall GATE in another place, but it works now, thank you very much!

María

**Comment by JannikStroetgen** [comment]
Thank you, @greenwoodma !
